---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
namespace: "sonarr"
namePrefix: "sonarr-"
images:
  - name: "linuxserver/sonarr"
    newTag: "3.0.10"
configMapGenerator:
  - name: app-config
    envs:
      - "app_config.env"
